package neuron_analyzer.controller;
import neuron_analyzer.model.*;
import neuron_analyzer.view.*;

/**
 * Observer interface for receiving events generated by the application's
 * custom {@code NTextField} numeric input widgets. Implementations are
 * registered with a field and are notified whenever the user commits a new
 * value so the surrounding UI or analysis code can react to the change.
 */
public interface NTextFieldListener {

	/**
	 * Called by an {@code NTextField} when its value changes or is committed.
	 * The source field is passed in so the listener can read the new contents,
	 * identify which control produced the event (when it is wired to more than
	 * one), and take appropriate action. The {@code e} parameter is the
	 * {@code NTextField} that fired the event.
	 */
	public void fireNTextFieldEvent(NTextField e);
}
